# Generated by Django 5.0.4 on 2024-04-21 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medico', '0003_datasabertas'),
        ('paciente', '0002_documento'),
    ]

    operations = [
        migrations.AddField(
            model_name='datasabertas',
            name='consultas',
            field=models.ManyToManyField(related_name='datas_abertas', to='paciente.consulta'),
        ),
    ]
