# Generated by Django 5.0.6 on 2024-05-31 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medico', '0004_alter_datasabertas_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dadosmedico',
            name='numero',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
